os:
  - osx
  - linux

language: node_js

node_js:
  - stable

script:
  - set -e
  - npm run lint
  - npm run build
  - npm run unit-tests
  - npm run publish

before_script:
  - echo "--before-script--"

before_install:
  - echo "--before-install--"

after_failure:
  - sleep 5
  - echo "--after-failure--"

after_script:
  - sleep 5
  - echo "--after-script--"

