os:
  - osx
  - linux

language: node_js

node_js:
  - 11

script:
  - set -e
  - echo "--script-before-sleep--"
  - sleep 10
  - echo "--script-after-sleep-"
  - npm run lint
  - npm run build
  - npm run unit-tests
  - npm run publish

after_failure:
  - sleep 5
  - echo "--after-failure--"

after_script:
  - sleep 5
  - echo "--after-script--"

